# Generated by Django 2.1.5 on 2019-01-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(default='', max_length=250),
        ),
    ]
