# Generated by Django 2.1.5 on 2019-01-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20190119_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
    ]
